name       : onedrive
version    : 2.3.5
release    : 6
source     :
    - https://github.com/abraunegg/onedrive/archive/v2.3.5.tar.gz : db8426faeaa93168a300b46b5a3890b5b69937658f093c36d3d1eabb223afdb7
license    : GPL-3.0-or-later
component  : network.clients
summary    : A complete tool to interact with OneDrive on Linux.
description: |
    CLI tool to access and update your OneDrive files. Featuring shared folders, support for OneDrive for Business, resumable uploads, real-time file monitoring and state caching.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - dmd
setup      : |
    # Remove unneeded "documentation" files
    %patch -p1 < $pkgfiles/remove_docs.patch

    %configure

    # Don't create var/log folder
    sed -i '/var/d' Makefile
build      : |
    %make
install    : |
    %make_install
