name       : onedrive
version    : 2.4.0
release    : 13
source     :
    - https://github.com/abraunegg/onedrive/archive/v2.4.0.tar.gz : 79575c47e6e90bacff00dad3c2de1e2a4251c74256717889a22c59862c614d3b
license    : GPL-3.0-or-later
component  : network.clients
summary    : A complete tool to interact with OneDrive on Linux.
description: |
    CLI tool to access and update your OneDrive files. Featuring shared folders, support for OneDrive for Business, resumable uploads, real-time file monitoring and state caching.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - dmd
setup      : |
    # Remove unneeded "documentation" files
    %patch -p1 < $pkgfiles/remove_docs.patch

    %configure
build      : |
    %make
install    : |
    %make_install
