name       : onedrive
version    : 1.1.3
release    : 1
source     :
    - https://github.com/skilion/onedrive/archive/v1.1.3.tar.gz : fb12235a73919b3374b8f27785b834a690fba1c6e70c6e6f1f5da3e51eb471a0
license    : GPL-3.0-or-later
component  : network.clients
summary    : A complete tool to interact with OneDrive on Linux.
description: |
    CLI tool to access and update your OneDrive files. Featuring shared folders, support for OneDrive for Business, resumable uploads, real-time file monitoring and state caching.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - dmd
setup      : |
    # Fix PREFIX
    sed -i 's/local//' Makefile
    # Use release version number instead of using git versions
    sed -i 's/version:.*/version:/' Makefile
    sed -i "s/echo.*/echo $version > version/" Makefile
build      : |
    %make
install    : |
    %make_install
