name       : onedrive
version    : 2.3.1
release    : 3
source     :
    - https://github.com/abraunegg/onedrive/archive/v2.3.1.tar.gz : e4b9c5c6b17df2ccf65305e6d2a955fa501f94577fb8522158e54de94e93bf0d
license    : GPL-3.0-or-later
component  : network.clients
summary    : A complete tool to interact with OneDrive on Linux.
description: |
    CLI tool to access and update your OneDrive files. Featuring shared folders, support for OneDrive for Business, resumable uploads, real-time file monitoring and state caching.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - dmd
setup      : |
    # Fix PREFIX
    sed -i 's/local//' Makefile

    # Don't create var/log folder
    sed -i '/var/d' Makefile
build      : |
    %make
install    : |
    %make_install
