name       : onedrive
version    : 2.3.2
release    : 4
source     :
    - https://github.com/abraunegg/onedrive/archive/v2.3.2.tar.gz : 0a6136b6204f835803ac71d3cdcd797604d1d078e17b00a7a1bb34ccad35fd0f
license    : GPL-3.0-or-later
component  : network.clients
summary    : A complete tool to interact with OneDrive on Linux.
description: |
    CLI tool to access and update your OneDrive files. Featuring shared folders, support for OneDrive for Business, resumable uploads, real-time file monitoring and state caching.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - dmd
setup      : |
    # Fix PREFIX
    sed -i 's/local//' Makefile

    # Don't create var/log folder
    sed -i '/var/d' Makefile
build      : |
    %make
install    : |
    %make_install
