name       : onedrive
version    : 2.4.3
release    : 16
source     :
    - https://github.com/abraunegg/onedrive/archive/v2.4.3.tar.gz : 4236f436b3658e360164d945a8bc5c9620539c1339ef9182e3d060d2e3b90b9b
license    : GPL-3.0-or-later
component  : network.clients
summary    : A complete tool to interact with OneDrive on Linux.
description: |
    CLI tool to access and update your OneDrive files. Featuring shared folders, support for OneDrive for Business, resumable uploads, real-time file monitoring and state caching.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - dmd
setup      : |
    # Remove unneeded "documentation" files
    %patch -p1 < $pkgfiles/remove_docs.patch

    %configure
build      : |
    %make
install    : |
    %make_install
