name       : onedrive
version    : 2.4.6
release    : 18
source     :
    - https://github.com/abraunegg/onedrive/archive/v2.4.6.tar.gz : 2c8551de6a8df5145162ee20169acea03873d20bf3a3490c749985ce43143b08
license    : GPL-3.0-or-later
component  : network.clients
summary    : A complete tool to interact with OneDrive on Linux.
description: |
    CLI tool to access and update your OneDrive files. Featuring shared folders, support for OneDrive for Business, resumable uploads, real-time file monitoring and state caching.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - dmd
setup      : |
    # Remove unneeded "documentation" files
    %patch -p1 < $pkgfiles/remove_docs.patch

    %reconfigure --enable-completions --with-zsh-completion-dir=/usr/share/zsh/site-functions --with-fish-completion-dir=/usr/share/fish/vendor_completions.d
build      : |
    %make
install    : |
    %make_install
