name       : onedrive
version    : 2.4.9
release    : 21
source     :
    - https://github.com/abraunegg/onedrive/archive/v2.4.9.tar.gz : 27be7a0e898a6e2aa425eaecb983def4e81147e2e453c36c63f584e8c999966a
license    : GPL-3.0-or-later
component  : network.clients
summary    : A complete tool to interact with OneDrive on Linux.
description: |
    CLI tool to access and update your OneDrive files. Featuring shared folders, support for OneDrive for Business, resumable uploads, real-time file monitoring and state caching.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - dmd
setup      : |
    # Remove unneeded "documentation" files
    %patch -p1 < $pkgfiles/remove_docs.patch

    %reconfigure --enable-completions --with-zsh-completion-dir=/usr/share/zsh/site-functions --with-fish-completion-dir=/usr/share/fish/vendor_completions.d
build      : |
    %make
install    : |
    %make_install
